command:
  description: Execute command in the shell
  fields:
    command: 
      example: "echo 'hello'"

commands:
  description: Execute commands in the shell
  fields:
    commands: 
      example: ["echo 'teste1'","echo 'teste2'"]
